name: FactionsPro
author: Tethered_, HostingItAll.com
description: A Plugin For Easily Managing Factions
version: 1.4.7 
main: FactionsPro\FactionMain
api: [4.0.0]
softdepend: ["PureChat", "AntiSpamPro"]
commands:
  f:
    description: use /f help for all parameters
    permission: f.command
permissions:
  f.command:
    default: true
    description: "Allow use of all faction commands"
  fac.override:
    default: op
    description: "Allows op users to override factions"
